#ifndef LIBJACKTRIP_GLOBAL_H
#define LIBJACKTRIP_GLOBAL_H
#ifndef STATIC_LIBJACKTRIP
#if defined(LIBJACKTRIP_LIBRARY)
#  define LIBJACKTRIP_EXPORT Q_DECL_EXPORT
#else
#  define LIBJACKTRIP_EXPORT Q_DECL_IMPORT
#endif


#else
#  define LIBJACKTRIP_EXPORT
#endif
#endif // LIBJACKTRIP_GLOBAL_H
